main: me.puyodead1.staffparticles.StaffParticles
version: 3.0.1
name: StaffParticles
api-version: 1.14
description: Staff Particles
author: Puyodead1
commands:
  staffparticles:
    description: Main Command