main: me.puyodead1.staffparticles.StaffParticles
version: 3.0
name: StaffParticles
api-version: 1.14
description: Thank You Amazing Staff!
author: Puyodead1
commands:
  staffparticles:
    description: Main Command